### PR TITLE
Update Quarto Rmd

### PR DESCRIPTION
**Pull request by ernst-paul**

### CODE REVIEW

**Review by gerkovink — APPROVED** [review]
Thanks, EP

**Comment by hanneoberman** [comment]
The tests fail with the following:
``` r
library(dessert);
fit <- lm(Petal.Length ~ ., data = iris);
dessert(fit, recipe = "regression")
#> [1] "method initialize"
#> [1] "dessert.lm"
#> Error in dessert.lm(self = <environment>): argument "dessert" is missing, with no default
```

<sup>Created on 2023-05-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hanneoberman** [comment]
No without errors:
``` r
library(dessert);
fit <- lm(Petal.Length ~ ., data = iris);
testthat::expect_no_error(dessert(fit, recipe = "regression"))
#> [1] "method initialize"
#> [1] "dessert.lm"
#> [1] "method render"
#> [31mdessert: qmd located
#> 
#> [0m[31mdessert: figures located
#> 
#> [0m[31mdessert: output folder created
#> 
#> [0m[31mdessert: qmd copies
#> 
#> [0m[31mdessert: figures copied
#> 
#> [0m[31mdessert: input object saved
#> 
#> [0m
#> 
#> processing file: regression.qmd
#>   |                                                   |                                           |   0%  |                                                   |..                                         |   4%                             |                                                   |...                                        |   8% (unnamed-chunk-1)           |                                                   |.....                                      |  12%                             |                                                   |.......                                    |  16% (unnamed-chunk-2)           |                                                   |.........                                  |  20%                             |                                                   |..........                                 |  24% (fig-lm-linearity)          |                                                   |............                               |  28%                             |                                                   |..............                             |  32% (fig-lm-normality)          |                                                   |...............                            |  36%                             |                                                   |.................                          |  40% (fig-lm-homoscedasticity)   |                                                   |...................                        |  44%                             |                                                   |.....................                      |  48% (fig-lm-independence)       |                                                   |......................                     |  52%                             |                                                   |........................                   |  56% (fig-lm-multicollinearity)  |                                                   |..........................                 |  60%                             |                                                   |............................               |  64% (fig-lm-leverage)           |                                                   |.............................              |  68%                             |                                                   |...............................            |  72% (unnamed-chunk-9)           |                                                   |.................................          |  76%                             |                                                   |..................................         |  80% (unnamed-chunk-10)          |                                                   |....................................       |  84%                             |                                                   |......................................     |  88% (unnamed-chunk-11)          |                                                   |........................................   |  92%                             |                                                   |.........................................  |  96% (unnamed-chunk-12)          |                                                   |...........................................| 100%                                                                                                                                                
#> output file: regression.knit.md
#> 
#> pandoc 
#>   to: html
#>   output-file: regression.html
#>   standalone: true
#>   embed-resources: true
#>   section-divs: true
#>   html-math-method: mathjax
#>   wrap: none
#>   default-image-extension: png
#>   number-sections: true
#>   toc: true
#>   
#> metadata
#>   document-css: false
#>   link-citations: true
#>   date-format: long
#>   lang: en
#>   title: Multiple Least Squares Regression
#>   subtitle: 'Generated by the R-package:  [`dessert`](https://github.com/gerkovink/dessert) &#x1F370;'
#>   authors:
#>     - name: G. Vink
#>       affiliations:
#>         - name: Utrecht University
#>           city: Utrecht
#>           state: Utrecht
#>     - name: H. I. Oberman
#>     - name: E. P. Swens
#>   title-block-banner: true
#>   editor: source
#>   number-depth: 3
#>   
#> Output created: regression.html
```

<sup>Created on 2023-05-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hanneoberman** [comment]
However, the tests do not run in the `test_that()` call:

ℹ Testing dessert
✔ | F W S  OK | Context
⠏ |         0 | dessert                           [1] "method initialize"
[1] "dessert.lm"
[1] "method render"
dessert: qmd located

✖ | 1       2 | dessert [0.9s]                    
──────────────────────────────────────────────────
Failure (test-dessert.R:5:1): (code run outside of `test_that()`)
Expected `dessert(fit, recipe = "regression")` to run without any errors.
ℹ Actually got a <simpleError>:
  Error in `dessert$render()`:
  ! Following figures not found: C:/Users/4216318/Desktop/dessert/inst/help/figures/lm-linearity.pngC:/Users/4216318/Desktop/dessert/inst/help/figures/lm-normality.pngC:/Users/4216318/Desktop/dessert/inst/help/figures/lm-homoscedasticity.pngC:/Users/4216318/Desktop/dessert/inst/help/figures/lm-independence.pngC:/Users/4216318/Desktop/dessert/inst/help/figures/lm-leverage-1.pngC:/Users/4216318/Desktop/dessert/inst/help/figures/lm-leverage-2.pngC:/Users/4216318/Desktop/dessert/inst/help/figures/lm-leverage-3.png
──────────────────────────────────────────────────

══ Results ═══════════════════════════════════════
Duration: 2.1 s

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 2 ]

**Comment by hanneoberman** [comment]
Never use 'fix' in your commit messages...
```
NOTE:
Namespaces in Imports field not imported from:
    ‘R6’ ‘rstudioapi’
    All declared Imports should be used.
```

**Pull request closed without merging**
